# create your drupal and postgres config here, based off the last assignment
version: '2.0'

services:
    drupal:
        image: drupal:8-apache
        ports:
            - "8080:80"
        volumes:
            - drupal-modules:/var/www/html/modules
            - drupal-profiles:/var/www/html/profiles
            - drupal-sites:/var/www/html/themes
            - drupal-themes:/var/www/html/sites

    postgres:
        image: postgres:10
        environment:
            POSTGRES_PASSWORD: example


volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes: